# Mail relay
- name: ensure postfix packages are installed
  yum: name={{ item }} state=present
  with_items:
    - postfix
  tags: ['postfix']

- name: ensure the postfix directory is configured
  file: path=/etc/postfix state=directory owner=root group=postfix mode=0750
  tags: ['postfix']

- name: template postfix config files
  template:
    src: "etc.postfix.{{ item }}.j2"
    dest: "/etc/postfix/{{ item }}"
    owner: root
    group: postfix
    mode: 0640
  with_items:
    - access
    - canonical
    - generic
    - header_checks
    - transport
    - main.cf
  notify: postfix restart
  tags: ['postfix']

- name: ensure other config files are removed
  file: path=/etc/postfix/{{ item }} state=absent
  with_items:
    - relocated
    - virtual
  tags: ['postfix']

- name: ensure allowed domains is present for internal mail relay
  template:
    src: etc.postfix.recipient_domains.j2
    dest: /etc/postfix/recipient_domains
    owner: root
    group: postfix
    mode: 0640
  notify: recipient_domains rebuild
  when: postfix_use_recipient_domains
  tags: ['postfix']

- name: ensure allowed domains is absent for external mail relay
  file: path={{ item }} state=absent
  with_items:
    - /etc/postfix/recipient_domains
    - /etc/postfix/recipient_domains.db
  when: not postfix_use_recipient_domains
  tags: ['postfix']

- name: ensure postfix is started and enabled
  service: name=postfix state=started enabled=yes
  tags: ['postfix']
