
- name: ensure postfix packages are installed
  yum: name={{ item }} state=present
  with_items:
    - postfix
    - cyrus-sasl
    - cyrus-sasl-lib
    - cyrus-sasl-plain
  tags: ['postfix']

- name: configure dkim signing (include)
  include: opendkim.yml
  when: postfix_enable_dkim == true
  tags: ['postfix']

- name: ensure the postfix directory is configured
  file: path=/etc/postfix state=directory owner=root group=postfix mode=0750
  tags: ['postfix']

- name: place postfix config file templates (maps)
  template:
    src: "etc.postfix.{{ item }}.j2"
    dest: "/etc/postfix/{{ item }}"
    owner: root
    group: postfix
    mode: 0640
  notify: "postfix {{ item }} rebuild"
  with_items:
    - access
    - generic
    - recipient_domains
    - sasl_passwd
    - sender_relay
    - transport
    - virtual
  tags: ['postfix']

- name: place postfix config file templates (static)
  template: 
    src: "etc.postfix.{{ item }}.j2"
    dest: "/etc/postfix/{{ item }}"
    owner: root 
    group: postfix 
    mode: 0640
  with_items:
    - bcc_map
    - canonical
    - header_checks
    - main.cf
  notify: postfix postfix reload
  tags: ['postfix']

- name: ensure other config files are removed
  file: path=/etc/postfix/{{ item }} state=absent
  with_items:
    - relocated
  notify: postfix postfix reload
  tags: ['postfix']

- name: place local mail aliases
  template:
    src: etc.aliases.j2
    dest: /etc/aliases
    owner: root
    group: postfix
    mode: 0640
  notify: postfix aliases rebuild
  tags: ['postfix']

- name: make maillog group readable for collectd
  file: path=/var/log/maillog state=touch owner=root group=collectd mode=0640
  when: setup_collectd
  tags: ['postfix', 'collectd']

- name: place the postfix_collectd config
  template:
    src: etc.collectd.d.{{ item }}
    dest: /etc/collectd.d/{{ item }}
    owner: root
    group: collectd
    mode: 0640
  with_items:
    - postfix_collectd.conf
  notify: restart collectd
  when: setup_collectd
  tags: ['postfix', 'collectd']

- name: place custom nagios plugins
  copy:
    src: usr.lib64.nagios.plugins.{{ item }}
    dest: /usr/lib64/nagios/plugins/{{ item }}
    owner: root
    group: root
    mode: 0755
  with_items:
    - check_relay_monitoring.sh
  when: setup_nagios
  tags: ['postfix', 'ncpa']

- name: ensure postfix is started and enabled
  service: name=postfix state=started enabled=yes
  tags: ['postfix']
